/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StructuredOutputRouteRouteImport } from './routes/_structured-output/route'
import { Route as ReportingRouteRouteImport } from './routes/_reporting/route'
import { Route as NpmGithubChatRouteRouteImport } from './routes/_npm-github-chat/route'
import { Route as HomeRouteRouteImport } from './routes/_home/route'
import { Route as ExecutePromptRouteRouteImport } from './routes/_execute-prompt/route'
import { Route as DatabaseDemoRouteRouteImport } from './routes/_database-demo/route'
import { Route as BankingDemoRouteRouteImport } from './routes/_banking-demo/route'
import { Route as HomeIndexRouteImport } from './routes/_home/index'
import { Route as StructuredOutputStructuredOutputRouteImport } from './routes/_structured-output/structured-output'
import { Route as ReportingReportingAgentRouteImport } from './routes/_reporting/reporting-agent'
import { Route as NpmGithubChatNpmGithubChatRouteImport } from './routes/_npm-github-chat/npm-github-chat'
import { Route as ExecutePromptExecutePromptRouteImport } from './routes/_execute-prompt/execute-prompt'
import { Route as DatabaseDemoDatabaseDemoRouteImport } from './routes/_database-demo/database-demo'
import { Route as BankingDemoBankingDemoRouteImport } from './routes/_banking-demo/banking-demo'
import { Route as StructuredOutputApiStructuredOutputSkillsRouteImport } from './routes/_structured-output/api.structured-output-skills'
import { Route as StructuredOutputApiStructuredOutputRouteImport } from './routes/_structured-output/api.structured-output'
import { Route as ReportingApiReportsRouteImport } from './routes/_reporting/api.reports'
import { Route as ReportingApiReportSseRouteImport } from './routes/_reporting/api.report-sse'
import { Route as ReportingApiReportEventRouteImport } from './routes/_reporting/api.report-event'
import { Route as ReportingApiReportDemoRouteImport } from './routes/_reporting/api.report-demo'
import { Route as ReportingApiInvalidateRouteImport } from './routes/_reporting/api.invalidate'
import { Route as NpmGithubChatApiGeneratePdfRouteImport } from './routes/_npm-github-chat/api.generate-pdf'
import { Route as NpmGithubChatApiCodemodeRouteImport } from './routes/_npm-github-chat/api.codemode'
import { Route as HomeApiSkillsRouteImport } from './routes/_home/api.skills'
import { Route as HomeApiProductRegularRouteImport } from './routes/_home/api.product-regular'
import { Route as HomeApiProductCodemodeRouteImport } from './routes/_home/api.product-codemode'
import { Route as ExecutePromptApiRealtimeTokenRouteImport } from './routes/_execute-prompt/api.realtime-token'
import { Route as ExecutePromptApiExecutePromptRouteImport } from './routes/_execute-prompt/api.execute-prompt'
import { Route as DatabaseDemoApiJudgeRouteImport } from './routes/_database-demo/api.judge'
import { Route as DatabaseDemoApiDbSkillsRouteImport } from './routes/_database-demo/api.db-skills'
import { Route as DatabaseDemoApiDatabaseDemoRouteImport } from './routes/_database-demo/api.database-demo'
import { Route as BankingDemoApiBankingInitRouteImport } from './routes/_banking-demo/api.banking-init'
import { Route as BankingDemoApiBankingDemoRouteImport } from './routes/_banking-demo/api.banking-demo'

const StructuredOutputRouteRoute = StructuredOutputRouteRouteImport.update({
  id: '/_structured-output',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportingRouteRoute = ReportingRouteRouteImport.update({
  id: '/_reporting',
  getParentRoute: () => rootRouteImport,
} as any)
const NpmGithubChatRouteRoute = NpmGithubChatRouteRouteImport.update({
  id: '/_npm-github-chat',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRouteRoute = HomeRouteRouteImport.update({
  id: '/_home',
  getParentRoute: () => rootRouteImport,
} as any)
const ExecutePromptRouteRoute = ExecutePromptRouteRouteImport.update({
  id: '/_execute-prompt',
  getParentRoute: () => rootRouteImport,
} as any)
const DatabaseDemoRouteRoute = DatabaseDemoRouteRouteImport.update({
  id: '/_database-demo',
  getParentRoute: () => rootRouteImport,
} as any)
const BankingDemoRouteRoute = BankingDemoRouteRouteImport.update({
  id: '/_banking-demo',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeIndexRoute = HomeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => HomeRouteRoute,
} as any)
const StructuredOutputStructuredOutputRoute =
  StructuredOutputStructuredOutputRouteImport.update({
    id: '/structured-output',
    path: '/structured-output',
    getParentRoute: () => StructuredOutputRouteRoute,
  } as any)
const ReportingReportingAgentRoute = ReportingReportingAgentRouteImport.update({
  id: '/reporting-agent',
  path: '/reporting-agent',
  getParentRoute: () => ReportingRouteRoute,
} as any)
const NpmGithubChatNpmGithubChatRoute =
  NpmGithubChatNpmGithubChatRouteImport.update({
    id: '/npm-github-chat',
    path: '/npm-github-chat',
    getParentRoute: () => NpmGithubChatRouteRoute,
  } as any)
const ExecutePromptExecutePromptRoute =
  ExecutePromptExecutePromptRouteImport.update({
    id: '/execute-prompt',
    path: '/execute-prompt',
    getParentRoute: () => ExecutePromptRouteRoute,
  } as any)
const DatabaseDemoDatabaseDemoRoute =
  DatabaseDemoDatabaseDemoRouteImport.update({
    id: '/database-demo',
    path: '/database-demo',
    getParentRoute: () => DatabaseDemoRouteRoute,
  } as any)
const BankingDemoBankingDemoRoute = BankingDemoBankingDemoRouteImport.update({
  id: '/banking-demo',
  path: '/banking-demo',
  getParentRoute: () => BankingDemoRouteRoute,
} as any)
const StructuredOutputApiStructuredOutputSkillsRoute =
  StructuredOutputApiStructuredOutputSkillsRouteImport.update({
    id: '/api/structured-output-skills',
    path: '/api/structured-output-skills',
    getParentRoute: () => StructuredOutputRouteRoute,
  } as any)
const StructuredOutputApiStructuredOutputRoute =
  StructuredOutputApiStructuredOutputRouteImport.update({
    id: '/api/structured-output',
    path: '/api/structured-output',
    getParentRoute: () => StructuredOutputRouteRoute,
  } as any)
const ReportingApiReportsRoute = ReportingApiReportsRouteImport.update({
  id: '/api/reports',
  path: '/api/reports',
  getParentRoute: () => ReportingRouteRoute,
} as any)
const ReportingApiReportSseRoute = ReportingApiReportSseRouteImport.update({
  id: '/api/report-sse',
  path: '/api/report-sse',
  getParentRoute: () => ReportingRouteRoute,
} as any)
const ReportingApiReportEventRoute = ReportingApiReportEventRouteImport.update({
  id: '/api/report-event',
  path: '/api/report-event',
  getParentRoute: () => ReportingRouteRoute,
} as any)
const ReportingApiReportDemoRoute = ReportingApiReportDemoRouteImport.update({
  id: '/api/report-demo',
  path: '/api/report-demo',
  getParentRoute: () => ReportingRouteRoute,
} as any)
const ReportingApiInvalidateRoute = ReportingApiInvalidateRouteImport.update({
  id: '/api/invalidate',
  path: '/api/invalidate',
  getParentRoute: () => ReportingRouteRoute,
} as any)
const NpmGithubChatApiGeneratePdfRoute =
  NpmGithubChatApiGeneratePdfRouteImport.update({
    id: '/api/generate-pdf',
    path: '/api/generate-pdf',
    getParentRoute: () => NpmGithubChatRouteRoute,
  } as any)
const NpmGithubChatApiCodemodeRoute =
  NpmGithubChatApiCodemodeRouteImport.update({
    id: '/api/codemode',
    path: '/api/codemode',
    getParentRoute: () => NpmGithubChatRouteRoute,
  } as any)
const HomeApiSkillsRoute = HomeApiSkillsRouteImport.update({
  id: '/api/skills',
  path: '/api/skills',
  getParentRoute: () => HomeRouteRoute,
} as any)
const HomeApiProductRegularRoute = HomeApiProductRegularRouteImport.update({
  id: '/api/product-regular',
  path: '/api/product-regular',
  getParentRoute: () => HomeRouteRoute,
} as any)
const HomeApiProductCodemodeRoute = HomeApiProductCodemodeRouteImport.update({
  id: '/api/product-codemode',
  path: '/api/product-codemode',
  getParentRoute: () => HomeRouteRoute,
} as any)
const ExecutePromptApiRealtimeTokenRoute =
  ExecutePromptApiRealtimeTokenRouteImport.update({
    id: '/api/realtime-token',
    path: '/api/realtime-token',
    getParentRoute: () => ExecutePromptRouteRoute,
  } as any)
const ExecutePromptApiExecutePromptRoute =
  ExecutePromptApiExecutePromptRouteImport.update({
    id: '/api/execute-prompt',
    path: '/api/execute-prompt',
    getParentRoute: () => ExecutePromptRouteRoute,
  } as any)
const DatabaseDemoApiJudgeRoute = DatabaseDemoApiJudgeRouteImport.update({
  id: '/api/judge',
  path: '/api/judge',
  getParentRoute: () => DatabaseDemoRouteRoute,
} as any)
const DatabaseDemoApiDbSkillsRoute = DatabaseDemoApiDbSkillsRouteImport.update({
  id: '/api/db-skills',
  path: '/api/db-skills',
  getParentRoute: () => DatabaseDemoRouteRoute,
} as any)
const DatabaseDemoApiDatabaseDemoRoute =
  DatabaseDemoApiDatabaseDemoRouteImport.update({
    id: '/api/database-demo',
    path: '/api/database-demo',
    getParentRoute: () => DatabaseDemoRouteRoute,
  } as any)
const BankingDemoApiBankingInitRoute =
  BankingDemoApiBankingInitRouteImport.update({
    id: '/api/banking-init',
    path: '/api/banking-init',
    getParentRoute: () => BankingDemoRouteRoute,
  } as any)
const BankingDemoApiBankingDemoRoute =
  BankingDemoApiBankingDemoRouteImport.update({
    id: '/api/banking-demo',
    path: '/api/banking-demo',
    getParentRoute: () => BankingDemoRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof HomeIndexRoute
  '/banking-demo': typeof BankingDemoBankingDemoRoute
  '/database-demo': typeof DatabaseDemoDatabaseDemoRoute
  '/execute-prompt': typeof ExecutePromptExecutePromptRoute
  '/npm-github-chat': typeof NpmGithubChatNpmGithubChatRoute
  '/reporting-agent': typeof ReportingReportingAgentRoute
  '/structured-output': typeof StructuredOutputStructuredOutputRoute
  '/api/banking-demo': typeof BankingDemoApiBankingDemoRoute
  '/api/banking-init': typeof BankingDemoApiBankingInitRoute
  '/api/database-demo': typeof DatabaseDemoApiDatabaseDemoRoute
  '/api/db-skills': typeof DatabaseDemoApiDbSkillsRoute
  '/api/judge': typeof DatabaseDemoApiJudgeRoute
  '/api/execute-prompt': typeof ExecutePromptApiExecutePromptRoute
  '/api/realtime-token': typeof ExecutePromptApiRealtimeTokenRoute
  '/api/product-codemode': typeof HomeApiProductCodemodeRoute
  '/api/product-regular': typeof HomeApiProductRegularRoute
  '/api/skills': typeof HomeApiSkillsRoute
  '/api/codemode': typeof NpmGithubChatApiCodemodeRoute
  '/api/generate-pdf': typeof NpmGithubChatApiGeneratePdfRoute
  '/api/invalidate': typeof ReportingApiInvalidateRoute
  '/api/report-demo': typeof ReportingApiReportDemoRoute
  '/api/report-event': typeof ReportingApiReportEventRoute
  '/api/report-sse': typeof ReportingApiReportSseRoute
  '/api/reports': typeof ReportingApiReportsRoute
  '/api/structured-output': typeof StructuredOutputApiStructuredOutputRoute
  '/api/structured-output-skills': typeof StructuredOutputApiStructuredOutputSkillsRoute
}
export interface FileRoutesByTo {
  '/': typeof HomeIndexRoute
  '/banking-demo': typeof BankingDemoBankingDemoRoute
  '/database-demo': typeof DatabaseDemoDatabaseDemoRoute
  '/execute-prompt': typeof ExecutePromptExecutePromptRoute
  '/npm-github-chat': typeof NpmGithubChatNpmGithubChatRoute
  '/reporting-agent': typeof ReportingReportingAgentRoute
  '/structured-output': typeof StructuredOutputStructuredOutputRoute
  '/api/banking-demo': typeof BankingDemoApiBankingDemoRoute
  '/api/banking-init': typeof BankingDemoApiBankingInitRoute
  '/api/database-demo': typeof DatabaseDemoApiDatabaseDemoRoute
  '/api/db-skills': typeof DatabaseDemoApiDbSkillsRoute
  '/api/judge': typeof DatabaseDemoApiJudgeRoute
  '/api/execute-prompt': typeof ExecutePromptApiExecutePromptRoute
  '/api/realtime-token': typeof ExecutePromptApiRealtimeTokenRoute
  '/api/product-codemode': typeof HomeApiProductCodemodeRoute
  '/api/product-regular': typeof HomeApiProductRegularRoute
  '/api/skills': typeof HomeApiSkillsRoute
  '/api/codemode': typeof NpmGithubChatApiCodemodeRoute
  '/api/generate-pdf': typeof NpmGithubChatApiGeneratePdfRoute
  '/api/invalidate': typeof ReportingApiInvalidateRoute
  '/api/report-demo': typeof ReportingApiReportDemoRoute
  '/api/report-event': typeof ReportingApiReportEventRoute
  '/api/report-sse': typeof ReportingApiReportSseRoute
  '/api/reports': typeof ReportingApiReportsRoute
  '/api/structured-output': typeof StructuredOutputApiStructuredOutputRoute
  '/api/structured-output-skills': typeof StructuredOutputApiStructuredOutputSkillsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_banking-demo': typeof BankingDemoRouteRouteWithChildren
  '/_database-demo': typeof DatabaseDemoRouteRouteWithChildren
  '/_execute-prompt': typeof ExecutePromptRouteRouteWithChildren
  '/_home': typeof HomeRouteRouteWithChildren
  '/_npm-github-chat': typeof NpmGithubChatRouteRouteWithChildren
  '/_reporting': typeof ReportingRouteRouteWithChildren
  '/_structured-output': typeof StructuredOutputRouteRouteWithChildren
  '/_banking-demo/banking-demo': typeof BankingDemoBankingDemoRoute
  '/_database-demo/database-demo': typeof DatabaseDemoDatabaseDemoRoute
  '/_execute-prompt/execute-prompt': typeof ExecutePromptExecutePromptRoute
  '/_npm-github-chat/npm-github-chat': typeof NpmGithubChatNpmGithubChatRoute
  '/_reporting/reporting-agent': typeof ReportingReportingAgentRoute
  '/_structured-output/structured-output': typeof StructuredOutputStructuredOutputRoute
  '/_home/': typeof HomeIndexRoute
  '/_banking-demo/api/banking-demo': typeof BankingDemoApiBankingDemoRoute
  '/_banking-demo/api/banking-init': typeof BankingDemoApiBankingInitRoute
  '/_database-demo/api/database-demo': typeof DatabaseDemoApiDatabaseDemoRoute
  '/_database-demo/api/db-skills': typeof DatabaseDemoApiDbSkillsRoute
  '/_database-demo/api/judge': typeof DatabaseDemoApiJudgeRoute
  '/_execute-prompt/api/execute-prompt': typeof ExecutePromptApiExecutePromptRoute
  '/_execute-prompt/api/realtime-token': typeof ExecutePromptApiRealtimeTokenRoute
  '/_home/api/product-codemode': typeof HomeApiProductCodemodeRoute
  '/_home/api/product-regular': typeof HomeApiProductRegularRoute
  '/_home/api/skills': typeof HomeApiSkillsRoute
  '/_npm-github-chat/api/codemode': typeof NpmGithubChatApiCodemodeRoute
  '/_npm-github-chat/api/generate-pdf': typeof NpmGithubChatApiGeneratePdfRoute
  '/_reporting/api/invalidate': typeof ReportingApiInvalidateRoute
  '/_reporting/api/report-demo': typeof ReportingApiReportDemoRoute
  '/_reporting/api/report-event': typeof ReportingApiReportEventRoute
  '/_reporting/api/report-sse': typeof ReportingApiReportSseRoute
  '/_reporting/api/reports': typeof ReportingApiReportsRoute
  '/_structured-output/api/structured-output': typeof StructuredOutputApiStructuredOutputRoute
  '/_structured-output/api/structured-output-skills': typeof StructuredOutputApiStructuredOutputSkillsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/banking-demo'
    | '/database-demo'
    | '/execute-prompt'
    | '/npm-github-chat'
    | '/reporting-agent'
    | '/structured-output'
    | '/api/banking-demo'
    | '/api/banking-init'
    | '/api/database-demo'
    | '/api/db-skills'
    | '/api/judge'
    | '/api/execute-prompt'
    | '/api/realtime-token'
    | '/api/product-codemode'
    | '/api/product-regular'
    | '/api/skills'
    | '/api/codemode'
    | '/api/generate-pdf'
    | '/api/invalidate'
    | '/api/report-demo'
    | '/api/report-event'
    | '/api/report-sse'
    | '/api/reports'
    | '/api/structured-output'
    | '/api/structured-output-skills'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/banking-demo'
    | '/database-demo'
    | '/execute-prompt'
    | '/npm-github-chat'
    | '/reporting-agent'
    | '/structured-output'
    | '/api/banking-demo'
    | '/api/banking-init'
    | '/api/database-demo'
    | '/api/db-skills'
    | '/api/judge'
    | '/api/execute-prompt'
    | '/api/realtime-token'
    | '/api/product-codemode'
    | '/api/product-regular'
    | '/api/skills'
    | '/api/codemode'
    | '/api/generate-pdf'
    | '/api/invalidate'
    | '/api/report-demo'
    | '/api/report-event'
    | '/api/report-sse'
    | '/api/reports'
    | '/api/structured-output'
    | '/api/structured-output-skills'
  id:
    | '__root__'
    | '/_banking-demo'
    | '/_database-demo'
    | '/_execute-prompt'
    | '/_home'
    | '/_npm-github-chat'
    | '/_reporting'
    | '/_structured-output'
    | '/_banking-demo/banking-demo'
    | '/_database-demo/database-demo'
    | '/_execute-prompt/execute-prompt'
    | '/_npm-github-chat/npm-github-chat'
    | '/_reporting/reporting-agent'
    | '/_structured-output/structured-output'
    | '/_home/'
    | '/_banking-demo/api/banking-demo'
    | '/_banking-demo/api/banking-init'
    | '/_database-demo/api/database-demo'
    | '/_database-demo/api/db-skills'
    | '/_database-demo/api/judge'
    | '/_execute-prompt/api/execute-prompt'
    | '/_execute-prompt/api/realtime-token'
    | '/_home/api/product-codemode'
    | '/_home/api/product-regular'
    | '/_home/api/skills'
    | '/_npm-github-chat/api/codemode'
    | '/_npm-github-chat/api/generate-pdf'
    | '/_reporting/api/invalidate'
    | '/_reporting/api/report-demo'
    | '/_reporting/api/report-event'
    | '/_reporting/api/report-sse'
    | '/_reporting/api/reports'
    | '/_structured-output/api/structured-output'
    | '/_structured-output/api/structured-output-skills'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  BankingDemoRouteRoute: typeof BankingDemoRouteRouteWithChildren
  DatabaseDemoRouteRoute: typeof DatabaseDemoRouteRouteWithChildren
  ExecutePromptRouteRoute: typeof ExecutePromptRouteRouteWithChildren
  HomeRouteRoute: typeof HomeRouteRouteWithChildren
  NpmGithubChatRouteRoute: typeof NpmGithubChatRouteRouteWithChildren
  ReportingRouteRoute: typeof ReportingRouteRouteWithChildren
  StructuredOutputRouteRoute: typeof StructuredOutputRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_structured-output': {
      id: '/_structured-output'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof StructuredOutputRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_reporting': {
      id: '/_reporting'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ReportingRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_npm-github-chat': {
      id: '/_npm-github-chat'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof NpmGithubChatRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_home': {
      id: '/_home'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof HomeRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_execute-prompt': {
      id: '/_execute-prompt'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ExecutePromptRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_database-demo': {
      id: '/_database-demo'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof DatabaseDemoRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_banking-demo': {
      id: '/_banking-demo'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof BankingDemoRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_home/': {
      id: '/_home/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof HomeIndexRouteImport
      parentRoute: typeof HomeRouteRoute
    }
    '/_structured-output/structured-output': {
      id: '/_structured-output/structured-output'
      path: '/structured-output'
      fullPath: '/structured-output'
      preLoaderRoute: typeof StructuredOutputStructuredOutputRouteImport
      parentRoute: typeof StructuredOutputRouteRoute
    }
    '/_reporting/reporting-agent': {
      id: '/_reporting/reporting-agent'
      path: '/reporting-agent'
      fullPath: '/reporting-agent'
      preLoaderRoute: typeof ReportingReportingAgentRouteImport
      parentRoute: typeof ReportingRouteRoute
    }
    '/_npm-github-chat/npm-github-chat': {
      id: '/_npm-github-chat/npm-github-chat'
      path: '/npm-github-chat'
      fullPath: '/npm-github-chat'
      preLoaderRoute: typeof NpmGithubChatNpmGithubChatRouteImport
      parentRoute: typeof NpmGithubChatRouteRoute
    }
    '/_execute-prompt/execute-prompt': {
      id: '/_execute-prompt/execute-prompt'
      path: '/execute-prompt'
      fullPath: '/execute-prompt'
      preLoaderRoute: typeof ExecutePromptExecutePromptRouteImport
      parentRoute: typeof ExecutePromptRouteRoute
    }
    '/_database-demo/database-demo': {
      id: '/_database-demo/database-demo'
      path: '/database-demo'
      fullPath: '/database-demo'
      preLoaderRoute: typeof DatabaseDemoDatabaseDemoRouteImport
      parentRoute: typeof DatabaseDemoRouteRoute
    }
    '/_banking-demo/banking-demo': {
      id: '/_banking-demo/banking-demo'
      path: '/banking-demo'
      fullPath: '/banking-demo'
      preLoaderRoute: typeof BankingDemoBankingDemoRouteImport
      parentRoute: typeof BankingDemoRouteRoute
    }
    '/_structured-output/api/structured-output-skills': {
      id: '/_structured-output/api/structured-output-skills'
      path: '/api/structured-output-skills'
      fullPath: '/api/structured-output-skills'
      preLoaderRoute: typeof StructuredOutputApiStructuredOutputSkillsRouteImport
      parentRoute: typeof StructuredOutputRouteRoute
    }
    '/_structured-output/api/structured-output': {
      id: '/_structured-output/api/structured-output'
      path: '/api/structured-output'
      fullPath: '/api/structured-output'
      preLoaderRoute: typeof StructuredOutputApiStructuredOutputRouteImport
      parentRoute: typeof StructuredOutputRouteRoute
    }
    '/_reporting/api/reports': {
      id: '/_reporting/api/reports'
      path: '/api/reports'
      fullPath: '/api/reports'
      preLoaderRoute: typeof ReportingApiReportsRouteImport
      parentRoute: typeof ReportingRouteRoute
    }
    '/_reporting/api/report-sse': {
      id: '/_reporting/api/report-sse'
      path: '/api/report-sse'
      fullPath: '/api/report-sse'
      preLoaderRoute: typeof ReportingApiReportSseRouteImport
      parentRoute: typeof ReportingRouteRoute
    }
    '/_reporting/api/report-event': {
      id: '/_reporting/api/report-event'
      path: '/api/report-event'
      fullPath: '/api/report-event'
      preLoaderRoute: typeof ReportingApiReportEventRouteImport
      parentRoute: typeof ReportingRouteRoute
    }
    '/_reporting/api/report-demo': {
      id: '/_reporting/api/report-demo'
      path: '/api/report-demo'
      fullPath: '/api/report-demo'
      preLoaderRoute: typeof ReportingApiReportDemoRouteImport
      parentRoute: typeof ReportingRouteRoute
    }
    '/_reporting/api/invalidate': {
      id: '/_reporting/api/invalidate'
      path: '/api/invalidate'
      fullPath: '/api/invalidate'
      preLoaderRoute: typeof ReportingApiInvalidateRouteImport
      parentRoute: typeof ReportingRouteRoute
    }
    '/_npm-github-chat/api/generate-pdf': {
      id: '/_npm-github-chat/api/generate-pdf'
      path: '/api/generate-pdf'
      fullPath: '/api/generate-pdf'
      preLoaderRoute: typeof NpmGithubChatApiGeneratePdfRouteImport
      parentRoute: typeof NpmGithubChatRouteRoute
    }
    '/_npm-github-chat/api/codemode': {
      id: '/_npm-github-chat/api/codemode'
      path: '/api/codemode'
      fullPath: '/api/codemode'
      preLoaderRoute: typeof NpmGithubChatApiCodemodeRouteImport
      parentRoute: typeof NpmGithubChatRouteRoute
    }
    '/_home/api/skills': {
      id: '/_home/api/skills'
      path: '/api/skills'
      fullPath: '/api/skills'
      preLoaderRoute: typeof HomeApiSkillsRouteImport
      parentRoute: typeof HomeRouteRoute
    }
    '/_home/api/product-regular': {
      id: '/_home/api/product-regular'
      path: '/api/product-regular'
      fullPath: '/api/product-regular'
      preLoaderRoute: typeof HomeApiProductRegularRouteImport
      parentRoute: typeof HomeRouteRoute
    }
    '/_home/api/product-codemode': {
      id: '/_home/api/product-codemode'
      path: '/api/product-codemode'
      fullPath: '/api/product-codemode'
      preLoaderRoute: typeof HomeApiProductCodemodeRouteImport
      parentRoute: typeof HomeRouteRoute
    }
    '/_execute-prompt/api/realtime-token': {
      id: '/_execute-prompt/api/realtime-token'
      path: '/api/realtime-token'
      fullPath: '/api/realtime-token'
      preLoaderRoute: typeof ExecutePromptApiRealtimeTokenRouteImport
      parentRoute: typeof ExecutePromptRouteRoute
    }
    '/_execute-prompt/api/execute-prompt': {
      id: '/_execute-prompt/api/execute-prompt'
      path: '/api/execute-prompt'
      fullPath: '/api/execute-prompt'
      preLoaderRoute: typeof ExecutePromptApiExecutePromptRouteImport
      parentRoute: typeof ExecutePromptRouteRoute
    }
    '/_database-demo/api/judge': {
      id: '/_database-demo/api/judge'
      path: '/api/judge'
      fullPath: '/api/judge'
      preLoaderRoute: typeof DatabaseDemoApiJudgeRouteImport
      parentRoute: typeof DatabaseDemoRouteRoute
    }
    '/_database-demo/api/db-skills': {
      id: '/_database-demo/api/db-skills'
      path: '/api/db-skills'
      fullPath: '/api/db-skills'
      preLoaderRoute: typeof DatabaseDemoApiDbSkillsRouteImport
      parentRoute: typeof DatabaseDemoRouteRoute
    }
    '/_database-demo/api/database-demo': {
      id: '/_database-demo/api/database-demo'
      path: '/api/database-demo'
      fullPath: '/api/database-demo'
      preLoaderRoute: typeof DatabaseDemoApiDatabaseDemoRouteImport
      parentRoute: typeof DatabaseDemoRouteRoute
    }
    '/_banking-demo/api/banking-init': {
      id: '/_banking-demo/api/banking-init'
      path: '/api/banking-init'
      fullPath: '/api/banking-init'
      preLoaderRoute: typeof BankingDemoApiBankingInitRouteImport
      parentRoute: typeof BankingDemoRouteRoute
    }
    '/_banking-demo/api/banking-demo': {
      id: '/_banking-demo/api/banking-demo'
      path: '/api/banking-demo'
      fullPath: '/api/banking-demo'
      preLoaderRoute: typeof BankingDemoApiBankingDemoRouteImport
      parentRoute: typeof BankingDemoRouteRoute
    }
  }
}

interface BankingDemoRouteRouteChildren {
  BankingDemoBankingDemoRoute: typeof BankingDemoBankingDemoRoute
  BankingDemoApiBankingDemoRoute: typeof BankingDemoApiBankingDemoRoute
  BankingDemoApiBankingInitRoute: typeof BankingDemoApiBankingInitRoute
}

const BankingDemoRouteRouteChildren: BankingDemoRouteRouteChildren = {
  BankingDemoBankingDemoRoute: BankingDemoBankingDemoRoute,
  BankingDemoApiBankingDemoRoute: BankingDemoApiBankingDemoRoute,
  BankingDemoApiBankingInitRoute: BankingDemoApiBankingInitRoute,
}

const BankingDemoRouteRouteWithChildren =
  BankingDemoRouteRoute._addFileChildren(BankingDemoRouteRouteChildren)

interface DatabaseDemoRouteRouteChildren {
  DatabaseDemoDatabaseDemoRoute: typeof DatabaseDemoDatabaseDemoRoute
  DatabaseDemoApiDatabaseDemoRoute: typeof DatabaseDemoApiDatabaseDemoRoute
  DatabaseDemoApiDbSkillsRoute: typeof DatabaseDemoApiDbSkillsRoute
  DatabaseDemoApiJudgeRoute: typeof DatabaseDemoApiJudgeRoute
}

const DatabaseDemoRouteRouteChildren: DatabaseDemoRouteRouteChildren = {
  DatabaseDemoDatabaseDemoRoute: DatabaseDemoDatabaseDemoRoute,
  DatabaseDemoApiDatabaseDemoRoute: DatabaseDemoApiDatabaseDemoRoute,
  DatabaseDemoApiDbSkillsRoute: DatabaseDemoApiDbSkillsRoute,
  DatabaseDemoApiJudgeRoute: DatabaseDemoApiJudgeRoute,
}

const DatabaseDemoRouteRouteWithChildren =
  DatabaseDemoRouteRoute._addFileChildren(DatabaseDemoRouteRouteChildren)

interface ExecutePromptRouteRouteChildren {
  ExecutePromptExecutePromptRoute: typeof ExecutePromptExecutePromptRoute
  ExecutePromptApiExecutePromptRoute: typeof ExecutePromptApiExecutePromptRoute
  ExecutePromptApiRealtimeTokenRoute: typeof ExecutePromptApiRealtimeTokenRoute
}

const ExecutePromptRouteRouteChildren: ExecutePromptRouteRouteChildren = {
  ExecutePromptExecutePromptRoute: ExecutePromptExecutePromptRoute,
  ExecutePromptApiExecutePromptRoute: ExecutePromptApiExecutePromptRoute,
  ExecutePromptApiRealtimeTokenRoute: ExecutePromptApiRealtimeTokenRoute,
}

const ExecutePromptRouteRouteWithChildren =
  ExecutePromptRouteRoute._addFileChildren(ExecutePromptRouteRouteChildren)

interface HomeRouteRouteChildren {
  HomeIndexRoute: typeof HomeIndexRoute
  HomeApiProductCodemodeRoute: typeof HomeApiProductCodemodeRoute
  HomeApiProductRegularRoute: typeof HomeApiProductRegularRoute
  HomeApiSkillsRoute: typeof HomeApiSkillsRoute
}

const HomeRouteRouteChildren: HomeRouteRouteChildren = {
  HomeIndexRoute: HomeIndexRoute,
  HomeApiProductCodemodeRoute: HomeApiProductCodemodeRoute,
  HomeApiProductRegularRoute: HomeApiProductRegularRoute,
  HomeApiSkillsRoute: HomeApiSkillsRoute,
}

const HomeRouteRouteWithChildren = HomeRouteRoute._addFileChildren(
  HomeRouteRouteChildren,
)

interface NpmGithubChatRouteRouteChildren {
  NpmGithubChatNpmGithubChatRoute: typeof NpmGithubChatNpmGithubChatRoute
  NpmGithubChatApiCodemodeRoute: typeof NpmGithubChatApiCodemodeRoute
  NpmGithubChatApiGeneratePdfRoute: typeof NpmGithubChatApiGeneratePdfRoute
}

const NpmGithubChatRouteRouteChildren: NpmGithubChatRouteRouteChildren = {
  NpmGithubChatNpmGithubChatRoute: NpmGithubChatNpmGithubChatRoute,
  NpmGithubChatApiCodemodeRoute: NpmGithubChatApiCodemodeRoute,
  NpmGithubChatApiGeneratePdfRoute: NpmGithubChatApiGeneratePdfRoute,
}

const NpmGithubChatRouteRouteWithChildren =
  NpmGithubChatRouteRoute._addFileChildren(NpmGithubChatRouteRouteChildren)

interface ReportingRouteRouteChildren {
  ReportingReportingAgentRoute: typeof ReportingReportingAgentRoute
  ReportingApiInvalidateRoute: typeof ReportingApiInvalidateRoute
  ReportingApiReportDemoRoute: typeof ReportingApiReportDemoRoute
  ReportingApiReportEventRoute: typeof ReportingApiReportEventRoute
  ReportingApiReportSseRoute: typeof ReportingApiReportSseRoute
  ReportingApiReportsRoute: typeof ReportingApiReportsRoute
}

const ReportingRouteRouteChildren: ReportingRouteRouteChildren = {
  ReportingReportingAgentRoute: ReportingReportingAgentRoute,
  ReportingApiInvalidateRoute: ReportingApiInvalidateRoute,
  ReportingApiReportDemoRoute: ReportingApiReportDemoRoute,
  ReportingApiReportEventRoute: ReportingApiReportEventRoute,
  ReportingApiReportSseRoute: ReportingApiReportSseRoute,
  ReportingApiReportsRoute: ReportingApiReportsRoute,
}

const ReportingRouteRouteWithChildren = ReportingRouteRoute._addFileChildren(
  ReportingRouteRouteChildren,
)

interface StructuredOutputRouteRouteChildren {
  StructuredOutputStructuredOutputRoute: typeof StructuredOutputStructuredOutputRoute
  StructuredOutputApiStructuredOutputRoute: typeof StructuredOutputApiStructuredOutputRoute
  StructuredOutputApiStructuredOutputSkillsRoute: typeof StructuredOutputApiStructuredOutputSkillsRoute
}

const StructuredOutputRouteRouteChildren: StructuredOutputRouteRouteChildren = {
  StructuredOutputStructuredOutputRoute: StructuredOutputStructuredOutputRoute,
  StructuredOutputApiStructuredOutputRoute:
    StructuredOutputApiStructuredOutputRoute,
  StructuredOutputApiStructuredOutputSkillsRoute:
    StructuredOutputApiStructuredOutputSkillsRoute,
}

const StructuredOutputRouteRouteWithChildren =
  StructuredOutputRouteRoute._addFileChildren(
    StructuredOutputRouteRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  BankingDemoRouteRoute: BankingDemoRouteRouteWithChildren,
  DatabaseDemoRouteRoute: DatabaseDemoRouteRouteWithChildren,
  ExecutePromptRouteRoute: ExecutePromptRouteRouteWithChildren,
  HomeRouteRoute: HomeRouteRouteWithChildren,
  NpmGithubChatRouteRoute: NpmGithubChatRouteRouteWithChildren,
  ReportingRouteRoute: ReportingRouteRouteWithChildren,
  StructuredOutputRouteRoute: StructuredOutputRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
